import type { User } from "../model/types";
import { v4 as uuidv4 } from "uuid";

export const dataUsers: User[] = [
  {
    id: uuidv4(),
    name: "Анна Кузнецова",
    email: "anna@example.com",
    role: "admin",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=1",
    age: 28,
    city: "Москва",
    phone: "+7 (495) 123-45-67",
    registeredAt: "2023-01-15",
    rating: 4.9,
  },
  {
    id: uuidv4(),
    name: "Иван Петров",
    email: "ivan@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=2",
    age: 34,
    city: "Санкт-Петербург",
    phone: "+7 (812) 987-65-43",
    registeredAt: "2023-02-20",
    rating: 4.3,
  },
  {
    id: uuidv4(),
    name: "Мария Смирнова",
    email: "maria@example.com",
    role: "user",
    isActive: false,
    avatar: "https://i.pravatar.cc/150?img=3",
    age: 25,
    city: "Казань",
    phone: "+7 (843) 555-12-34",
    registeredAt: "2023-03-10",
    rating: 4.6,
  },
  {
    id: uuidv4(),
    name: "Алексей Иванов",
    email: "alex@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=4",
    age: 41,
    city: "Новосибирск",
    phone: "+7 (383) 222-33-44",
    registeredAt: "2023-01-05",
    rating: 4.2,
  },
  {
    id: uuidv4(),
    name: "Елена Попова",
    email: "elena@example.com",
    role: "user",
    isActive: false,
    avatar: "https://i.pravatar.cc/150?img=5",
    age: 29,
    city: "Екатеринбург",
    phone: "+7 (343) 777-88-99",
    registeredAt: "2023-04-18",
    rating: 4.5,
  },
  {
    id: uuidv4(),
    name: "Дмитрий Соколов",
    email: "dmitry@example.com",
    role: "admin",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=6",
    age: 37,
    city: "Москва",
    phone: "+7 (495) 444-55-66",
    registeredAt: "2023-02-28",
    rating: 4.8,
  },
  {
    id: uuidv4(),
    name: "Ольга Васильева",
    email: "olga@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=7",
    age: 32,
    city: "Нижний Новгород",
    phone: "+7 (831) 111-22-33",
    registeredAt: "2023-05-12",
    rating: 4.4,
  },
  {
    id: uuidv4(),
    name: "Павел Морозов",
    email: "pavel@example.com",
    role: "user",
    isActive: false,
    avatar: "https://i.pravatar.cc/150?img=8",
    age: 26,
    city: "Ростов-на-Дону",
    phone: "+7 (863) 999-00-11",
    registeredAt: "2023-06-25",
    rating: 4.0,
  },
  {
    id: uuidv4(),
    name: "Татьяна Новикова",
    email: "tatiana@example.com",
    role: "admin",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=9",
    age: 45,
    city: "Самара",
    phone: "+7 (846) 333-44-55",
    registeredAt: "2023-01-30",
    rating: 4.7,
  },
  {
    id: uuidv4(),
    name: "Сергей Козлов",
    email: "sergey@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=10",
    age: 22,
    city: "Уфа",
    phone: "+7 (347) 777-66-55",
    registeredAt: "2023-07-07",
    rating: 4.1,
  },
  {
    id: uuidv4(),
    name: "Юлия Зайцева",
    email: "yulia@example.com",
    role: "user",
    isActive: false,
    avatar: "https://i.pravatar.cc/150?img=11",
    age: 31,
    city: "Волгоград",
    phone: "+7 (844) 222-33-44",
    registeredAt: "2023-08-19",
    rating: 4.3,
  },
  {
    id: uuidv4(),
    name: "Андрей Лебедев",
    email: "andrey@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=12",
    age: 38,
    city: "Красноярск",
    phone: "+7 (391) 555-66-77",
    registeredAt: "2023-09-02",
    rating: 4.5,
  },
  {
    id: uuidv4(),
    name: "Кристина Белова",
    email: "kristina@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=13",
    age: 27,
    city: "Пермь",
    phone: "+7 (342) 101-20-30",
    registeredAt: "2023-10-11",
    rating: 4.6,
  },
  {
    id: uuidv4(),
    name: "Никита Фомин",
    email: "nikita@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=14",
    age: 30,
    city: "Тюмень",
    phone: "+7 (3452) 12-34-56",
    registeredAt: "2023-11-03",
    rating: 4.2,
  },
  {
    id: uuidv4(),
    name: "Виктория Орлова",
    email: "victoria@example.com",
    role: "admin",
    isActive: false,
    avatar: "https://i.pravatar.cc/150?img=15",
    age: 36,
    city: "Омск",
    phone: "+7 (3812) 65-43-21",
    registeredAt: "2023-12-09",
    rating: 4.4,
  },
  {
    id: uuidv4(),
    name: "Роман Гусев",
    email: "roman@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=16",
    age: 24,
    city: "Челябинск",
    phone: "+7 (351) 909-08-07",
    registeredAt: "2024-01-17",
    rating: 4.1,
  },
  {
    id: uuidv4(),
    name: "Алина Королева",
    email: "alina@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=17",
    age: 33,
    city: "Воронеж",
    phone: "+7 (473) 808-70-60",
    registeredAt: "2024-02-26",
    rating: 4.7,
  },
  {
    id: uuidv4(),
    name: "Максим Ефремов",
    email: "maxim@example.com",
    role: "user",
    isActive: false,
    avatar: "https://i.pravatar.cc/150?img=18",
    age: 40,
    city: "Иркутск",
    phone: "+7 (3952) 77-88-99",
    registeredAt: "2024-03-14",
    rating: 4.0,
  },
  {
    id: uuidv4(),
    name: "Светлана Демина",
    email: "svetlana@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=19",
    age: 29,
    city: "Калининград",
    phone: "+7 (4012) 44-55-66",
    registeredAt: "2024-04-08",
    rating: 4.8,
  },
  {
    id: uuidv4(),
    name: "Григорий Алексеев",
    email: "grigory@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=20",
    age: 35,
    city: "Сочи",
    phone: "+7 (862) 123-98-76",
    registeredAt: "2024-04-21",
    rating: 4.5,
  },
  {
    id: uuidv4(),
    name: "Полина Егорова",
    email: "polina@example.com",
    role: "admin",
    isActive: false,
    avatar: "https://i.pravatar.cc/150?img=21",
    age: 42,
    city: "Ярославль",
    phone: "+7 (4852) 70-80-90",
    registeredAt: "2024-05-02",
    rating: 4.6,
  },
  {
    id: uuidv4(),
    name: "Владимир Титов",
    email: "vladimir@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=22",
    age: 31,
    city: "Тула",
    phone: "+7 (4872) 55-66-77",
    registeredAt: "2024-05-19",
    rating: 4.3,
  },
  {
    id: uuidv4(),
    name: "Инна Федорова",
    email: "inna@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=23",
    age: 27,
    city: "Тверь",
    phone: "+7 (4822) 11-22-33",
    registeredAt: "2024-06-03",
    rating: 4.4,
  },
  {
    id: uuidv4(),
    name: "Артем Савельев",
    email: "artem@example.com",
    role: "user",
    isActive: false,
    avatar: "https://i.pravatar.cc/150?img=24",
    age: 39,
    city: "Хабаровск",
    phone: "+7 (4212) 88-77-66",
    registeredAt: "2024-06-14",
    rating: 4.2,
  },
  {
    id: uuidv4(),
    name: "Марина Тимофеева",
    email: "marina@example.com",
    role: "admin",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=25",
    age: 44,
    city: "Владивосток",
    phone: "+7 (423) 200-10-20",
    registeredAt: "2024-07-01",
    rating: 4.9,
  },
  {
    id: uuidv4(),
    name: "Денис Барсуков",
    email: "denis@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=26",
    age: 23,
    city: "Рязань",
    phone: "+7 (4912) 99-88-77",
    registeredAt: "2024-07-18",
    rating: 4.0,
  },
  {
    id: uuidv4(),
    name: "Ксения Чернова",
    email: "ksenia@example.com",
    role: "user",
    isActive: false,
    avatar: "https://i.pravatar.cc/150?img=27",
    age: 34,
    city: "Астрахань",
    phone: "+7 (8512) 45-67-89",
    registeredAt: "2024-08-06",
    rating: 4.3,
  },
  {
    id: uuidv4(),
    name: "Егор Мельников",
    email: "egor@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=28",
    age: 28,
    city: "Киров",
    phone: "+7 (8332) 33-22-11",
    registeredAt: "2024-08-27",
    rating: 4.5,
  },
  {
    id: uuidv4(),
    name: "Лилия Никитина",
    email: "lilia@example.com",
    role: "admin",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=29",
    age: 37,
    city: "Пенза",
    phone: "+7 (8412) 66-55-44",
    registeredAt: "2024-09-09",
    rating: 4.7,
  },
  {
    id: uuidv4(),
    name: "Степан Романов",
    email: "stepan@example.com",
    role: "user",
    isActive: false,
    avatar: "https://i.pravatar.cc/150?img=30",
    age: 32,
    city: "Ставрополь",
    phone: "+7 (8652) 12-21-12",
    registeredAt: "2024-09-30",
    rating: 4.1,
  },
  {
    id: uuidv4(),
    name: "Дарья Макарова",
    email: "daria.makarova@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=31",
    age: 26,
    city: "Белгород",
    phone: "+7 (4722) 10-20-30",
    registeredAt: "2024-10-06",
    rating: 4.4,
  },
  {
    id: uuidv4(),
    name: "Олег Данилов",
    email: "oleg.danilov@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=32",
    age: 36,
    city: "Сургут",
    phone: "+7 (3462) 54-32-10",
    registeredAt: "2024-10-18",
    rating: 4.2,
  },
  {
    id: uuidv4(),
    name: "Надежда Климова",
    email: "nadezhda.klimova@example.com",
    role: "admin",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=33",
    age: 39,
    city: "Курск",
    phone: "+7 (4712) 31-41-51",
    registeredAt: "2024-10-24",
    rating: 4.8,
  },
  {
    id: uuidv4(),
    name: "Илья Богданов",
    email: "ilya.bogdanov@example.com",
    role: "user",
    isActive: false,
    avatar: "https://i.pravatar.cc/150?img=34",
    age: 29,
    city: "Томск",
    phone: "+7 (3822) 60-50-40",
    registeredAt: "2024-11-02",
    rating: 4.0,
  },
  {
    id: uuidv4(),
    name: "Анастасия Павлова",
    email: "anastasia.pavlova@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=35",
    age: 31,
    city: "Ижевск",
    phone: "+7 (3412) 77-11-22",
    registeredAt: "2024-11-10",
    rating: 4.6,
  },
  {
    id: uuidv4(),
    name: "Руслан Жуков",
    email: "ruslan.zhukov@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=36",
    age: 27,
    city: "Липецк",
    phone: "+7 (4742) 22-44-66",
    registeredAt: "2024-11-19",
    rating: 4.3,
  },
  {
    id: uuidv4(),
    name: "Валерия Киселева",
    email: "valeria.kiseleva@example.com",
    role: "user",
    isActive: false,
    avatar: "https://i.pravatar.cc/150?img=37",
    age: 33,
    city: "Оренбург",
    phone: "+7 (3532) 12-34-98",
    registeredAt: "2024-11-28",
    rating: 4.1,
  },
  {
    id: uuidv4(),
    name: "Константин Матвеев",
    email: "konstantin.matveev@example.com",
    role: "admin",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=38",
    age: 43,
    city: "Брянск",
    phone: "+7 (4832) 90-80-70",
    registeredAt: "2024-12-05",
    rating: 4.9,
  },
  {
    id: uuidv4(),
    name: "Вероника Дорофеева",
    email: "veronika.dorofeeva@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=39",
    age: 24,
    city: "Смоленск",
    phone: "+7 (4812) 56-78-90",
    registeredAt: "2024-12-14",
    rating: 4.2,
  },
  {
    id: uuidv4(),
    name: "Михаил Рябов",
    email: "mikhail.ryabov@example.com",
    role: "user",
    isActive: false,
    avatar: "https://i.pravatar.cc/150?img=40",
    age: 38,
    city: "Архангельск",
    phone: "+7 (8182) 44-33-22",
    registeredAt: "2024-12-26",
    rating: 4.0,
  },
  {
    id: uuidv4(),
    name: "София Гаврилова",
    email: "sofia.gavrilova@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=41",
    age: 30,
    city: "Мурманск",
    phone: "+7 (8152) 99-77-55",
    registeredAt: "2025-01-07",
    rating: 4.7,
  },
  {
    id: uuidv4(),
    name: "Тимур Котов",
    email: "timur.kotov@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=42",
    age: 35,
    city: "Набережные Челны",
    phone: "+7 (8552) 12-12-12",
    registeredAt: "2025-01-15",
    rating: 4.4,
  },
  {
    id: uuidv4(),
    name: "Злата Селезнева",
    email: "zlata.selezneva@example.com",
    role: "admin",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=43",
    age: 41,
    city: "Саранск",
    phone: "+7 (8342) 88-66-44",
    registeredAt: "2025-01-24",
    rating: 4.8,
  },
  {
    id: uuidv4(),
    name: "Петр Логинов",
    email: "petr.loginov@example.com",
    role: "user",
    isActive: false,
    avatar: "https://i.pravatar.cc/150?img=44",
    age: 28,
    city: "Орёл",
    phone: "+7 (4862) 23-45-67",
    registeredAt: "2025-02-01",
    rating: 4.1,
  },
  {
    id: uuidv4(),
    name: "Яна Назарова",
    email: "yana.nazarova@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=45",
    age: 29,
    city: "Тамбов",
    phone: "+7 (4752) 11-33-55",
    registeredAt: "2025-02-12",
    rating: 4.5,
  },
  {
    id: uuidv4(),
    name: "Глеб Тарасов",
    email: "gleb.tarasov@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=46",
    age: 32,
    city: "Вологда",
    phone: "+7 (8172) 24-68-90",
    registeredAt: "2025-02-21",
    rating: 4.3,
  },
  {
    id: uuidv4(),
    name: "Карина Прохорова",
    email: "karina.prokhorova@example.com",
    role: "user",
    isActive: false,
    avatar: "https://i.pravatar.cc/150?img=47",
    age: 34,
    city: "Череповец",
    phone: "+7 (8202) 70-71-72",
    registeredAt: "2025-03-04",
    rating: 4.2,
  },
  {
    id: uuidv4(),
    name: "Федор Панин",
    email: "fedor.panin@example.com",
    role: "admin",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=48",
    age: 46,
    city: "Кострома",
    phone: "+7 (4942) 90-10-20",
    registeredAt: "2025-03-16",
    rating: 4.9,
  },
  {
    id: uuidv4(),
    name: "Милана Ларионова",
    email: "milana.larionova@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=49",
    age: 25,
    city: "Псков",
    phone: "+7 (8112) 30-40-50",
    registeredAt: "2025-03-27",
    rating: 4.4,
  },
  {
    id: uuidv4(),
    name: "Богдан Николаев",
    email: "bogdan.nikolaev@example.com",
    role: "user",
    isActive: false,
    avatar: "https://i.pravatar.cc/150?img=50",
    age: 37,
    city: "Йошкар-Ола",
    phone: "+7 (8362) 66-77-88",
    registeredAt: "2025-04-05",
    rating: 4.0,
  },
  {
    id: uuidv4(),
    name: "Элина Осипова",
    email: "elina.osipova@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=51",
    age: 28,
    city: "Сыктывкар",
    phone: "+7 (8212) 21-43-65",
    registeredAt: "2025-04-17",
    rating: 4.6,
  },
  {
    id: uuidv4(),
    name: "Лев Колесников",
    email: "lev.kolesnikov@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=52",
    age: 33,
    city: "Петрозаводск",
    phone: "+7 (8142) 45-45-45",
    registeredAt: "2025-04-28",
    rating: 4.3,
  },
  {
    id: uuidv4(),
    name: "Вера Макеева",
    email: "vera.makeeva@example.com",
    role: "admin",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=53",
    age: 40,
    city: "Ульяновск",
    phone: "+7 (8422) 14-28-56",
    registeredAt: "2025-05-09",
    rating: 4.8,
  },
  {
    id: uuidv4(),
    name: "Игнат Елисеев",
    email: "ignat.eliseev@example.com",
    role: "user",
    isActive: false,
    avatar: "https://i.pravatar.cc/150?img=54",
    age: 31,
    city: "Чебоксары",
    phone: "+7 (8352) 88-99-00",
    registeredAt: "2025-05-20",
    rating: 4.1,
  },
  {
    id: uuidv4(),
    name: "Алла Савина",
    email: "alla.savina@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=55",
    age: 35,
    city: "Балашиха",
    phone: "+7 (495) 770-88-11",
    registeredAt: "2025-06-01",
    rating: 4.5,
  },
  {
    id: uuidv4(),
    name: "Юрий Демидов",
    email: "yury.demidov@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=56",
    age: 27,
    city: "Подольск",
    phone: "+7 (4967) 33-44-55",
    registeredAt: "2025-06-13",
    rating: 4.2,
  },
  {
    id: uuidv4(),
    name: "Кира Меркулова",
    email: "kira.merkulova@example.com",
    role: "user",
    isActive: false,
    avatar: "https://i.pravatar.cc/150?img=57",
    age: 29,
    city: "Мытищи",
    phone: "+7 (495) 620-10-20",
    registeredAt: "2025-06-24",
    rating: 4.0,
  },
  {
    id: uuidv4(),
    name: "Станислав Чистяков",
    email: "stanislav.chistyakov@example.com",
    role: "admin",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=58",
    age: 44,
    city: "Химки",
    phone: "+7 (495) 300-40-50",
    registeredAt: "2025-07-07",
    rating: 4.9,
  },
  {
    id: uuidv4(),
    name: "Агата Виноградова",
    email: "agata.vinogradova@example.com",
    role: "user",
    isActive: true,
    avatar: "https://i.pravatar.cc/150?img=59",
    age: 26,
    city: "Королёв",
    phone: "+7 (495) 511-22-33",
    registeredAt: "2025-07-19",
    rating: 4.4,
  },
  {
    id: uuidv4(),
    name: "Родион Фролов",
    email: "rodion.frolov@example.com",
    role: "user",
    isActive: false,
    avatar: "https://i.pravatar.cc/150?img=60",
    age: 38,
    city: "Люберцы",
    phone: "+7 (495) 700-88-99",
    registeredAt: "2025-07-31",
    rating: 4.1,
  },
];
